name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:  # This enables manual triggering

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            rid: linux-x64
            binary_name: todoist-tui
          - os: windows-latest
            rid: win-x64
            binary_name: todoist-tui.exe
          - os: macos-latest
            rid: osx-x64
            binary_name: todoist-tui

    steps:
      - uses: actions/checkout@v3
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'
          
      - name: Publish
        run: |
          dotnet publish Console/Console.fsproj -c Release -r ${{ matrix.rid }} --self-contained true -o publish/${{ matrix.rid }} -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true
          echo "Build output directory:"
          ls -R publish/
        
      - name: Get Commit Hash
        id: commit
        run: echo "hash=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
        
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            publish/${{ matrix.rid }}/${{ matrix.binary_name }}
          tag_name: commit-${{ steps.commit.outputs.hash }}
          name: Release from commit ${{ steps.commit.outputs.hash }}
          body: |
            Automated release from main branch
            Commit: ${{ github.sha }}
            Triggered by: ${{ github.event_name }}
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
          fail_on_unmatched_files: false 