name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'
          
      - name: Publish
        run: |
          dotnet publish Console/Console.fsproj -c Release -r linux-x64 --self-contained true -o publish -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true
          ls -l publish/todoist-tui

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: publish/todoist-tui
          tag_name: latest
          name: Latest Release
          body: |
            Latest release from main branch
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }} 